name: CustomMessages
version: 2.4.6
main: com.psyco.tplmc.CustomMessages.CustomMessages
description: Changes server messages
authors: [robertoccu, psycowithespn]
soft-depend: [Vault]
commands:
    cm:
        description: Custom Messages command
        aliases: [custommessages]
        usage: /<command>
permissions:
    CustomMessages.*:
        description: Gives access to all CustomMessages Commands
        children:
            CustomMessages.join: true
            CustomMessages.quit: true
            CustomMessages.firstjoin: true
            CustomMessages.globaljoin: true
            CustomMessages.globalquit: true
            CustomMessages.join.other: true
            CustomMessages.quit.other: true
            CustomMessages.join.group: true
            CustomMessages.quit.group: true
            CustomMessages.noprefix: true
            CustomMessages.reload: true
            CustomMessages.join.disable: true
            CustomMessages.quit.disable: true
            CustomMessages.morevariables: true
            CustomMessages.colors: true
    CustomMessages.join:
        description: Allows you to set and reset your join message
        default: op
    CustomMessages.quit:
        description: Allows you to set and reset your quit message
        default: op
    CustomMessages.firstjoin:
        description: Allows you to set and reset the server's first join message
        default: op
    CustomMessages.kick:
        description: Allows you to set and reset the server's kick message
        default: op
    CustomMessages.globaljoin:
        description: Allows you to set and reset your server's join message
        default: op
    CustomMessages.globalquit:
        description: Allows you to set and reset your server's quit message
        default: op
    CustomMessages.join.other:
        description: Allows you to set and reset another's join message
        default: op
    CustomMessages.quit.other:
        description: Allows you to set and reset another's quit message
        default: op
    CustomMessages.join.group:
        description: Allows setting and resetting of a group's join message
        default: op
    CustomMessages.quit.group:
        description: Allows setting and resetting of a group's quit message
        default: op
    CustomMessages.noprefix:
        description: Does not show the message prefix
        default: op
    CustomMessages.reload:
        description: Allows you to reload
        default: op
    CustomMessages.join.disable:
        description: Allows you to disable and enable your join message
        default: op
    CustomMessages.quit.disable:
        description: Allows you to disable and enable your quit message
        default: op
    CustomMessages.morevariables:
        description: Allows you to put more variables in addition to /name and /nname
        default: op
    CustomMessages.colors:
        description: Allows you to use colors on yours messages
        default: op