name: CustomMessages
version: 2.0
main: com.psyco.tplmc.CustomMessages.CustomMessages
authors: [psycowithespn]
commands:
    cm:
        description: Custom Messages command
        aliases: [custommessages]
        usage: /<command>
permissions:
    CustomMessages.*:
        description: Gives access to all CustomMessages Commands
        children:
            CustomMessages.join: true
            CustomMessages.quit: true
            CustomMessages.globaljoin: true
            CustomMessages.globalquit: true
            CustomMessages.join.other: true
            CustomMessages.quit.other: true
            CustomMessages.noprefix: true
    CustomMessages.join:
        description: Allows you to set and reset your join message
        default: op
    CustomMessages.quit:
        description: Allows you to set and reset your quit message
        default: op
    CustomMessages.globaljoin:
        description: Allows you to set and reset your server's join message
        default: op
    CustomMessages.globalquit:
        description: Allows you to set and reset your server's quit message
        default: op
    CustomMessages.join.other:
        description: Allows you to set and reset another's join message
        default: op
    CustomMessages.quit.other:
        description: Allows you to set and reset another's quit message
        default: op
    CustomMessages.noprefix:
        description: Does not show the message prefix
        default: op